name: CI
on:
  push:
jobs:
  build:
    name: ${{ matrix.os.name }}-${{ matrix.framework }}
    runs-on: ${{ matrix.os.platform }}
    strategy:
      matrix:
        os:
          - platform: windows-2019
            name: Windows
          - platform: ubuntu-20.04
            name: Linux
        framework: [ net472, netcoreapp3.1, net6.0 ]
        exclude:
          - os:
              name: Windows
            framework: net472
      fail-fast: false
    steps:
      - run: echo "${{ matrix.os.name}}-${{ matrix.framework }} on ${{ matrix.os.platform }}"
